### ISSUE TITLE
Precompiled extension?

### ISSUE THREAD

**Issue by Romchikus** [BASI-LABS/parseltongue#5]
Having problems with npm and nodejs on windows, can we get precompiled ver, so it's only download and install for dummies like me who cannot install and compile dependencies through terminal tools?

**Comment by LVivona** [comment]
We are currently looking on making our extension available in the Google Chrome and Firefox stores to ensure easy access for all users.

but unfortunately In the meantime, I provided the ``/dist`` so you can you can manually add the extension by following these steps:

For Google Chrome:

    - Open chrome://extensions/ in your browser.
    - Enable "Developer mode" (toggle switch at the top right).
    - Click "Load unpacked" and select the dist folder of the extension.

For Firefox:

    - Open about:debugging#/runtime/this-firefox in your browser.
    - Click "Load Temporary Add-on."
    - Select any file in the dist folder of the extension.

**Comment by Romchikus** [comment]
Ok I thought my old issues were based on what I described above. I thought I had to compile it for the best work. But actually my chrome bugs are still there. I'm not sure the UI is correct. I see no place to write prompt in or any right click options. And also I have some errors in extensions tap. Changing manifest on v2 didn't help and there were other errors.
![image](https://github.com/user-attachments/assets/bc5ea8fd-ac99-4947-96db-cdb71817ac01)
![image](https://github.com/user-attachments/assets/8a8d017d-fd20-4922-bbff-e2ebe375874e)

**Comment by LVivona** [comment]
- Actually that's right you need to open the side-panel now.
-  I would pull the recent changes to fix that uncaught reference error, I fixed that activeElement
- The last error, I have not seen, so I'm not sure why it's not establishing the connection, so I'll see if I can replicate it.

<img width="295" alt="image" src="https://github.com/user-attachments/assets/21902dd6-8868-4e05-b883-2cc82156630f">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/f08a60f6-2167-4d60-8e30-c3fbae0e92e8">
